baseURL = "https://plumblinks.com/"
languageCode = "en-us"
title = "Plumblinks"
theme = "Eclectic"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

# Define the number of posts per page
paginate = 10

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
    
[Author] # Used in authorbox
  name = "Michael Johas Teener"
  bio = "MJT is the 'Godfather of Firewire' and was the instigator and longtime chair of the IEEE 802.1 Time-sensitive Networking group."
  avatar = "https://www.gravatar.com/avatar/46b7d7a97c42688b463a6c85b6ac42b1"

[Params]
  title = "Plumblinks" # Deprecated in favor of .Site.Params.logo.subtitle
  defaultDescription = " ... the MJT biz" # Site description. Used in meta description
  profilePicture = "images/MikeSummer2021.jpg"
# Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "gofw" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

# Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"


 [menu]
 
 # Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+1-831-824-4228"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/mikejt"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/mjohasteener"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com/gofw"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

    [permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true


[params.footer.recent_posts]
    enable = true